export const GAME = Object.freeze({
  width: 600,
  height: 900,
  playTop: 62,
  playBottom: 890,
  paddle: { width: 96, height: 14, y: 852, speed: 420 },
  ball: {
    radius: 6,
    derivedRadius: 3.75,
    speed: 600,
    maxSpeed: 1000,
  },
  autoFireInterval: 3,
  combo: {
    windowSeconds: 3,
    multiplierPerKill: 0.1,
    maximumMultiplier: 3,
  },
  upgrade: {
    scoreInterval: 2000,
    scoreGrowthCoefficient: 0.18,
    scoreGrowthExponent: 1.25,
    scoreCostRounding: 100,
    rapidFireMultiplier: 0.86,
    minimumFireInterval: 0.75,
    extraBallChancePerLevel: 0.2,
    topLaunchChance: 0.25,
    topLaunchSpeedMultiplier: 2,
    topLaunchMaxLevel: 1,
    topRecoveryChancePerLevel: 0.25,
    topRecoveryMaxLevel: 3,
    blastLaunchChance: 0.25,
    blastLaunchMaxLevel: 1,
    blastInterval: 1.5,
    blastIntervalMultiplierPerLevel: 0.8,
    blastMinimumInterval: 0.5,
    blastCooldownMaxLevel: 3,
    blastRadius: 90,
    blastDamage: 1,
    voidOrbitChance: 0.25,
    voidOrbitMaxLevel: 1,
    voidOrbitRadius: 26,
    voidOrbiterRadius: 5,
    voidOrbiterAngularSpeed: 4.2,
    voidOrbiterDamage: 1,
    ballSpeedMultiplierPerLevel: 1.12,
    paddleLengthMultiplierPerLevel: 1.2,
    paddleLengthMaxLevel: 5,
    bottomBounceChancePerLevel: 0.2,
    bottomBounceMaxLevel: 3,
    randomLaunchMinAngle: 0.35,
  },
  brick: {
    minWidth: 41,
    maxWidth: 74,
    minHeight: 32,
    maxHeight: 56,
    widthBiasExponent: 0.55,
    heightBiasExponent: 1.75,
    spawnLaneCount: 8,
    spawnSideMargin: 36,
    initialSpeed: 12,
    speedGrowthPerSecond: 0.22,
    maxSpeed: 48,
    initialSpawnInterval: 2.7,
    minSpawnInterval: 1.15,
    clearRefillCount: 8,
    bossWaveInterval: 180,
    bossMinionCount: 6,
    bossWidth: 115,
    bossHeight: 62,
    bossHealthMultiplier: 8,
    bossScoreMultiplier: 3,
    healthFormula: {
      // 期望血量 = baseHp
      //   + timeCoefficient * (存活分钟数 ^ timeExponent)
      //   + scoreCoefficient * ((分数 / scoreScale) ^ scoreExponent)
      baseHp: 1.4,
      timeCoefficient: 0.75,
      timeExponent: 1.1,
      scoreCoefficient: 1.1,
      scoreScale: 5000,
      scoreExponent: 0.55,
      randomSpread: 0.35,
      sizeMinMultiplier: 0.72,
      sizeMaxMultiplier: 1.35,
      sizeExponent: 0.9,
      minHp: 1,
    },
  },
});

export const COLORS = Object.freeze({
  background: '#070b18',
  grid: 'rgba(104, 131, 189, 0.065)',
  cyan: '#55e8ff',
  violet: '#8b7cff',
  pink: '#ff5cab',
  orange: '#ff9b54',
  text: '#dceaff',
});
