export const GAME = Object.freeze({
  width: 600,
  height: 900,
  playTop: 62,
  playBottom: 890,
  combat: {
    valueScale: 10,
    baseDamage: 10,
    baseHealth: 10,
  },
  paddle: { width: 96, height: 14, y: 852, speed: 420 },
  ball: {
    radius: 6,
    derivedRadius: 3.75,
    speed: 600,
    maxSpeed: 1000,
    defaultLevel: 1,
    defaultLives: 1,
    levelKillThresholds: Object.freeze([3, 9]),
    levelDamageBonus: 5,
    levelLivesBonus: 2,
    levelLivesBonusLevel: 3,
    levelBlastDamageBonus: 3,
    levelBlastRadiusBonus: 20,
    levelLightningDamageBonus: 3,
    levelLightningTargetBonus: 1,
    levelVoidOrbiterBonus: 1,
  },
  autoFireInterval: 3,
  collectible: {
    damagePercentPerLevel: 0.01,
    rareFlatDamagePerLevel: 3,
    epicFlatDamagePerLevel: 5,
    commonFireIntervalReduction: 0.015,
    rareFireIntervalReduction: 0.04,
    epicFireIntervalReduction: 0.1,
    minimumFireIntervalMultiplier: 0.25,
    extraSpecialBallChancePerLevel: 0.02,
    paddleWidthPercentPerLevel: 0.025,
    bottomRetentionChancePerLevel: 0.02,
    bonusExperienceChancePerLevel: 0.05,
    recoilDamagePercentPerLevel: 0.1,
    topSpeedDamageScalePerLevel: 0.05,
    blastFlatDamagePerLevel: 3,
    blastRadiusPerLevel: 10,
    voidRadiusPercentPerLevel: 0.02,
    voidSpeedPercentPerLevel: 0.02,
    navigationDamagePercentPerLevel: 0.05,
    lightningEchoChancePerLevel: 0.05,
    bossExtraDropChancePerLevel: 0.05,
    experiencePercentPerLevel: 0.05,
  },
  combo: {
    windowSeconds: 3,
    multiplierPerKill: 0.06,
    maximumMultiplier: 2,
  },
  worldLevel: {
    // 世界等级本身没有玩法上限；下列幂函数参数可以独立调节长期曲线。
    defaultLevel: 1,
    unlockBossWave: 7,
    enemyHealthCoefficient: 0.18,
    enemyHealthExponent: 1.35,
    bossHealthCoefficient: 0.06,
    bossHealthExponent: 1.25,
    scoreCoefficient: 0.12,
    scoreExponent: 1.18,
    bonusChestCoefficient: 0.04,
    bonusChestExponent: 0.72,
    // 只用于防止 JavaScript 数值溢出，不是可达到的玩法等级上限。
    maximumNumericValue: Number.MAX_SAFE_INTEGER,
  },
  upgrade: {
    scoreInterval: 2000,
    scoreGrowthCoefficient: 0.18,
    scoreGrowthExponent: 1.25,
    scoreLateGrowthStart: 8,
    scoreLateGrowthCoefficient: 0.025,
    scoreLateGrowthExponent: 2.05,
    scoreCostRounding: 100,
    rapidFireMultiplier: 0.86,
    rapidFireMaxLevel: 5,
    minimumFireInterval: 0.75,
    extraBallChancePerLevel: 0.2,
    multiShotMaxLevel: 10,
    doubleShotMaxLevel: 1,
    rapidVolleyChancePerLevel: 0.05,
    rapidVolleyMaxLevel: 3,
    rapidVolleyBallCount: 5,
    rapidVolleyShotInterval: 0.09,
    topLaunchSpeedMultiplier: 2,
    topLaunchMaxLevel: 1,
    topRecoveryChancePerLevel: 0.25,
    topRecoveryMaxLevel: 3,
    topImpactDamageScalePerLevel: 0.5,
    topImpactMaxLevel: 3,
    blastLaunchMaxLevel: 1,
    blastInterval: 1.5,
    blastIntervalMultiplierPerLevel: 0.8,
    blastMinimumInterval: 0.5,
    blastCooldownMaxLevel: 3,
    blastRadius: 90,
    blastDamage: 10,
    blastImpactChancePerLevel: 0.2,
    blastImpactMaxLevel: 3,
    voidOrbitMaxLevel: 1,
    voidOrbitRadius: 34,
    voidOrbiterRadius: 5,
    voidOrbiterAngularSpeed: 4.2,
    voidOrbiterSpeedMultiplierPerLevel: 1.25,
    voidOrbiterSpeedMaxLevel: 3,
    voidOrbitRadiusMultiplierPerLevel: 1.2,
    voidOrbitRadiusMaxLevel: 3,
    voidOrbiterDamage: 10,
    microNavigationMaxLevel: 1,
    navigationStrength: 0.55,
    navigationStrengthMultiplierPerLevel: 1.4,
    navigationStrengthMaxLevel: 3,
    navigationRange: 260,
    navigationReturnChancePerLevel: 0.15,
    navigationReturnMaxLevel: 3,
    navigationReturnDelay: 0.1,
    navigationReturnChainDecay: 0.6,
    lightningMaxLevel: 1,
    lightningDamage: 10,
    lightningAdditionalTargets: 1,
    lightningAdditionalTargetsPerLevel: 1,
    lightningJumpsMaxLevel: 3,
    lightningRange: 165,
    lightningStrikeChancePerLevel: 0.15,
    lightningStrikeMaxLevel: 3,
    ballSpeedMultiplierPerLevel: 1.12,
    ballSpeedMaxLevel: 3,
    ballDamagePerLevel: 1,
    ballDamageMaxLevel: 99,
    ballDamageOfferChance: 0.08,
    ballLivesPerLevel: 1,
    ballLivesMaxLevel: 2,
    paddleLengthMultiplierPerLevel: 1.2,
    paddleLengthMaxLevel: 5,
    doublePaddleMaxLevel: 3,
    doublePaddleWidthRatioPerLevel: 1 / 3,
    doublePaddleVerticalOffset: 72,
    bottomBounceChancePerLevel: 0.2,
    bottomBounceMaxLevel: 3,
    randomLaunchMinAngle: 0.35,
  },
  brick: {
    minWidth: 41,
    maxWidth: 74,
    minHeight: 32,
    maxHeight: 56,
    widthBiasExponent: 0.55,
    heightBiasExponent: 1.75,
    spawnLaneCount: 8,
    spawnSideMargin: 36,
    initialSpeed: 12,
    speedGrowthPerSecond: 0.22,
    maxSpeed: 48,
    initialSpawnInterval: 2.7,
    minSpawnInterval: 1.15,
    clearRefillCount: 8,
    bossWaveInterval: 180,
    bossRushStartWave: 7,
    bossRushRespawnDelay: 6,
    bossRushHealthMultiplierPerWave: 5,
    bossMinionCount: 6,
    bossWidth: 130,
    bossHeight: 70,
    bossHealthMultiplier: 12,
    // 只给世界 1 的首个 Boss 提供入门缓冲，不影响其奖励和后续 Boss。
    worldOneFirstBossHealthMultiplier: 0.8,
    bossScoreMultiplier: 3,
    lateGame: {
      // 前四个 Boss 保持原节奏；第 5 个 Boss 起进入终局压力阶段。
      startBossWave: 5,
      healthMultiplierPerWave: 1.42,
      // Boss 专属耐久在终局阶段快速抬升，目标是在第 6～7 波形成致命输出检查。
      bossHealthMultiplierPerWave: 4,
      spawnIntervalMultiplierPerWave: 0.88,
      minimumSpawnInterval: 0.68,
      bossMinionBonusPerWave: 2,
      bossMinionBonusCap: 6,
      // 后期耐久增长只按较低指数转化为分数，避免形成额外升级滚雪球。
      rewardGrowthExponent: 0.35,
    },
    healthFormula: {
      // 期望血量 = baseHp
      //   + timeCoefficient * (存活分钟数 ^ timeExponent)
      //   + scoreCoefficient * ((分数 / scoreScale) ^ scoreExponent)
      baseHp: 14,
      timeCoefficient: 7.5,
      timeExponent: 1.1,
      scoreCoefficient: 11,
      scoreScale: 5000,
      scoreExponent: 0.55,
      randomSpread: 3.5,
      sizeMinMultiplier: 0.72,
      sizeMaxMultiplier: 1.35,
      sizeExponent: 0.9,
      minHp: 10,
    },
  },
});

export const COLORS = Object.freeze({
  background: '#070b18',
  grid: 'rgba(104, 131, 189, 0.065)',
  cyan: '#55e8ff',
  violet: '#8b7cff',
  pink: '#ff5cab',
  orange: '#ff9b54',
  text: '#dceaff',
});
