-- 在 Supabase Dashboard -> SQL Editor 中执行一次。
-- 玩家名称允许重复；auth.users.id 才是玩家的唯一身份。

create table if not exists public.player_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(trim(display_name)) between 1 and 16),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.game_runs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  score bigint not null default 0,
  duration_seconds numeric(10, 2) not null default 0,
  channel text not null check (channel in ('stable', 'beta')),
  game_version text not null,
  upgrades jsonb not null default '{}'::jsonb,
  world_level bigint not null default 1 check (world_level >= 1),
  created_at timestamptz not null default now()
);

-- 兼容已经执行过旧版 schema.sql 的项目；历史成绩按世界等级 1 处理。
alter table public.game_runs
  add column if not exists world_level bigint not null default 1 check (world_level >= 1);

create index if not exists game_runs_leaderboard_idx
  on public.game_runs (channel, score desc, created_at asc);
create index if not exists game_runs_user_idx
  on public.game_runs (user_id, channel, score desc);

alter table public.player_profiles enable row level security;
alter table public.game_runs enable row level security;

drop policy if exists "Players can read their own profile" on public.player_profiles;
create policy "Players can read their own profile"
  on public.player_profiles for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Players can create their own profile" on public.player_profiles;
create policy "Players can create their own profile"
  on public.player_profiles for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Players can update their own profile" on public.player_profiles;
create policy "Players can update their own profile"
  on public.player_profiles for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Players can submit their own runs" on public.game_runs;
create policy "Players can submit their own runs"
  on public.game_runs for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

-- 返回列新增 world_level 时 PostgreSQL 不允许直接改变旧函数的返回类型。
drop function if exists public.get_leaderboard(text, integer);

create function public.get_leaderboard(
  p_channel text,
  p_limit integer default 20
)
returns table (
  rank bigint,
  player_code text,
  display_name text,
  score bigint,
  world_level bigint,
  duration_seconds numeric,
  created_at timestamptz,
  is_current boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  with personal_bests as (
    select distinct on (runs.user_id)
      runs.user_id,
      runs.score,
      runs.world_level,
      runs.duration_seconds,
      runs.created_at
    from public.game_runs as runs
    where runs.channel = p_channel
    order by runs.user_id, runs.score desc, runs.duration_seconds desc, runs.created_at asc
  ), ranked as (
    select
      row_number() over (order by best.score desc, best.duration_seconds desc, best.created_at asc) as rank,
      best.user_id,
      upper(substr(replace(best.user_id::text, '-', ''), 1, 4)) as player_code,
      profile.display_name,
      best.score,
      best.world_level,
      best.duration_seconds,
      best.created_at
    from personal_bests as best
    join public.player_profiles as profile on profile.user_id = best.user_id
  )
  select
    ranked.rank,
    ranked.player_code,
    ranked.display_name,
    ranked.score,
    ranked.world_level,
    ranked.duration_seconds,
    ranked.created_at,
    ranked.user_id = (select auth.uid()) as is_current
  from ranked
  order by ranked.rank
  limit greatest(1, least(coalesce(p_limit, 20), 100));
$$;

revoke all on function public.get_leaderboard(text, integer) from public;
grant execute on function public.get_leaderboard(text, integer) to anon, authenticated;
